name = "maintenance"
type = "javascript"
account_id = "aa6a672906a96132f0ffdc582c69537a"
zone_id = "f14939370d152d28d026295478d20daa"
kv_namespaces = [
  { binding = "KV", id = "20667e84f04843c883d31d8d48f2500a" }
]

[build]
command = "npm ci && npm run build && cd workers && npm ci && npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
entry-point = "./workers"
