name = "maintenance"
main = "./workers/dist/index.js"
account_id = "aa6a672906a96132f0ffdc582c69537a"
workers_dev = false
compatibility_date = "2022-07-19"

[[kv_namespaces]]
binding = "CONFIG"
id = "e210960e515040dbac47a542b5efd90f"
preview_id = "348375916100463baca31f7dc6680b6f"

[build]
command = "npm run build && cd workers && npm run build"

[site]
bucket = "./dist"
